Repository kyma-project/eventing-publisher-proxy, pull requests merged in 2023-12, with the labels that each got.

#8 Updated codeowners
  CODEOWNERS
Labels: cla: yes, size/M, lgtm

#9 Refactored makefile
  .gitignore
  Dockerfile
  Makefile
Labels: cla: yes, size/L, lgtm

#15 Replaced kyma/epp package with local EPP package and fixed lint issues
  cmd/event-publisher-proxy/main.go
  go.mod
  pkg/application/clean_test.go
  pkg/application/fake/lister.go
  pkg/application/lister.go
  pkg/cloudevents/builder/eventmesh.go
  pkg/cloudevents/builder/eventmesh_test.go
  pkg/cloudevents/builder/generic.go
  pkg/cloudevents/builder/generic_test.go
  pkg/cloudevents/builder/types.go
  pkg/cloudevents/eventtype/clean.go
  pkg/cloudevents/eventtype/clean_test.go
  pkg/cloudevents/eventtype/eventtypetest/eventtypetest.go
  pkg/cloudevents/eventtype/parse.go
  pkg/cloudevents/utils_test.go
  pkg/commander/eventmesh/eventmesh.go
  pkg/commander/nats/nats.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/handler/handler_v1alpha1_test.go
  pkg/informers/sync.go
  pkg/legacy/error_responses.go
  pkg/legacy/helpers.go
  pkg/legacy/legacy.go
  pkg/legacy/legacy_test.go
  pkg/metrics/collector.go
  pkg/metrics/collector_test.go
  pkg/metrics/histogram/mocks/BucketsProvider.go
  pkg/metrics/metricstest/metricstest.go
  pkg/nats/connect.go
  pkg/nats/connect_test.go
  pkg/oauth/client.go
  pkg/oauth/client_test.go
  pkg/oauth/config.go
  pkg/oauth/config_test.go
  pkg/receiver/receiver_test.go
  pkg/sender/common/backendpublisherror.go
  pkg/sender/eventmesh/eventmesh.go
  pkg/sender/eventmesh/eventmesh_test.go
  pkg/sender/jetstream/health.go
  pkg/sender/jetstream/jetstream.go
  pkg/sender/jetstream/jetstream_test.go
  pkg/signals/signals.go
  pkg/subscribed/helpers.go
  pkg/subscribed/processor.go
  pkg/subscribed/response.go
  pkg/tracing/propagation/tracecontextb3/http_format.go
  testing/env_config.go
  testing/fixtures.go
  testing/nats.go
  testing/utils.go
Labels: cla: yes, size/XL, lgtm

#17 Replaced eventing-controller pkg with eventing-manager
  Makefile
  cmd/event-publisher-proxy/main.go
  go.mod
  go.sum
  pkg/application/lister.go
  pkg/cloudevents/builder/eventmesh.go
  pkg/cloudevents/builder/eventmesh_test.go
  pkg/cloudevents/builder/generic.go
  pkg/cloudevents/builder/generic_test.go
  pkg/cloudevents/builder/types.go
  pkg/cloudevents/eventtype/clean.go
  pkg/cloudevents/eventtype/clean_test.go
  pkg/commander/eventmesh/eventmesh.go
  pkg/commander/nats/nats.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/handler/handler_v1alpha1_test.go
  pkg/informers/sync.go
  pkg/legacy/helpers.go
  pkg/metrics/collector_test.go
  pkg/metrics/server.go
  pkg/receiver/receiver.go
  pkg/receiver/receiver_test.go
  pkg/sender/common/backendpublisherror.go
  pkg/sender/eventmesh/eventmesh.go
  pkg/sender/eventmesh/eventmesh_test.go
  pkg/sender/jetstream/jetstream.go
  pkg/sender/jetstream/jetstream_test.go
  pkg/subscribed/helpers.go
  pkg/subscribed/helpers_test.go
  pkg/subscribed/processor.go
  pkg/subscribed/response.go
  pkg/tracing/helpers_test.go
  testing/nats.go
  testing/utils.go
Labels: cla: yes, size/L, lgtm

#20 Add security scanner config
  sec-scanners-config.yaml
Labels: cla: yes, size/S, lgtm

#26 Updated Readme
  README.md
  config/event-publisher-proxy/300-deployment.yaml
Labels: cla: yes, size/L, lgtm

#21 Setup EPP pipelines
  .github/workflows/lint-markdown-links.yml
  .github/workflows/lint.yml
  .github/workflows/unit-test.yml
Labels: cla: yes, size/L, lgtm

#25 Replaced pkg for application
  go.mod
  go.sum
  pkg/application/applicationtest/applicationtest.go
  pkg/application/clean.go
  pkg/application/clean_test.go
  pkg/application/fake/lister.go
  pkg/application/lister.go
Labels: cla: yes, size/S, lgtm

#28 Change event-publisher-proxy to eventing-publisher-proxy
  Dockerfile
  Makefile
  cmd/eventing-publisher-proxy/main.go
  config/event-publisher-proxy/300-deployment.yaml
Labels: cla: yes, size/S, lgtm
