Repository kyma-project/eventing-publisher-proxy, pull requests merged in 2024-02, with the labels that each got.

#71 Fix lint: goerr113
  .github/workflows/lint-go.yml
  pkg/application/lister.go
  pkg/cloudevents/builder/generic.go
  pkg/cloudevents/eventtype/parse.go
  pkg/handler/handler_v1alpha1_test.go
  pkg/nats/connect.go
  pkg/signals/signals.go
Labels: cla: yes, area/cli, size/M, kind/cleanup, lgtm

#72 Fix lint - funlen - thelper - perfsprint - godox - goconst
  .github/workflows/lint-go.yml
  pkg/commander/eventmesh/eventmesh.go
  pkg/commander/nats/nats.go
  pkg/handler/handler_v1alpha1_test.go
  pkg/handler/health/health_test.go
  pkg/legacy/legacytest/test.go
  pkg/metrics/collector.go
  pkg/metrics/metricstest/metricstest.go
  pkg/receiver/receiver_test.go
  pkg/sender/jetstream/jetstream_test.go
  pkg/subscribed/helpers.go
  pkg/subscribed/helpers_test.go
  pkg/tracing/helpers.go
  testing/fixtures.go
  testing/mock_server.go
Labels: cla: yes, area/cli, size/M, kind/cleanup, lgtm

#77 docs: Apply flexible Alerts plugin for EPP
  docs/user/README.md
Labels: documentation, cla: yes, size/S, kind/chore, area/documentation, lgtm

#76 feat: add rules for PRs
  .github/dependabot.yml
  .github/workflows/lint-conventional-prs.yml
Labels: cla: yes, size/M, lgtm

#88 chore: change dependabot config to weekly schedule
  .github/dependabot.yml
Labels: cla: yes, size/S, lgtm

#89 Chore: Bump Go version in go.mod
  .github/workflows/e2e.yml
  go.mod
  go.sum
Labels: cla: yes, size/M, lgtm

#91 fix: schedule of dependabot
  .github/dependabot.yml
Labels: cla: yes, size/XS, lgtm
