Repository kyma-project/eventing-publisher-proxy, pull requests merged in 2024-09, with the labels that each got.

#156 chore: upgrade golangci-lint version to v1.60.3
  .github/workflows/lint-go.yml
Labels: cla: yes, size/XS, lgtm

#158 chore: update image version to 1.1.0
  sec-scanners-config.yaml
Labels: cla: yes, size/XS, lgtm

#159 chore: update image version for release 1.1.0
  sec-scanners-config.yaml
Labels: cla: yes, size/XS, lgtm

#160 docs: add mandatory sections to the main reamde
  README.md
Labels: cla: yes, size/S, lgtm

#167 chore: added github action based build jobs
  .github/pull-build-image.yaml
  .github/push-build-image.yaml
  .github/tag-build-image.yaml
Labels: cla: yes, size/L, lgtm

#169 chore: replace prow build job waiting with github action
  .github/workflows/create-release.yaml
  .github/workflows/e2e.yml
Labels: cla: yes, size/M, lgtm

#170 chore: upgrade golang to 1.23.1
  Dockerfile
  go.mod
Labels: cla: yes, size/XS, lgtm
