Repository kyma-project/eventing-publisher-proxy, pull requests merged in 2024-01, with the labels that each got.

#31 Add release flow
  .github/workflows/create-release.yaml
  scripts/check_tag_info.sh
  scripts/create_changelog.sh
  scripts/create_draft_release.sh
  scripts/get_next_release_version.sh
  scripts/publish_release.sh
  scripts/verify_status.sh
Labels: cla: yes, size/L, lgtm

#30 Setup E2E test using NATS Backend
  .github/workflows/e2e.yml
  hack/ci/Makefile
  hack/get_kyma_file_name.sh
Labels: cla: yes, size/L, lgtm

#32 Release workflow
  .github/workflows/create-release.yaml
  scripts/check_tags_in_sec_scanners_config.sh
  scripts/create_changelog.sh
  scripts/create_draft_release.sh
  scripts/get_next_release_version.sh
  scripts/publish_release.sh
  scripts/verify_prow_post_job_status.sh
  sec-scanners-config.yaml
Labels: cla: yes, size/L, lgtm

#34 Add release changes
  .github/workflows/create-release.yaml
  .github/workflows/e2e.yml
  hack/ci/Makefile
  hack/get_kyma_file_name.sh
  scripts/check_tags_in_sec_scanners_config.sh
  scripts/create_changelog.sh
  scripts/create_draft_release.sh
  scripts/get_next_release_version.sh
  scripts/publish_release.sh
  scripts/verify_prow_post_job_status.sh
  sec-scanners-config.yaml
Labels: cla: yes, size/L, lgtm

#35 Fix referencing of env variable
  .github/workflows/create-release.yaml
Labels: cla: yes, size/XS, lgtm

#36 Release 0.0
  .github/workflows/create-release.yaml
Labels: cla: yes, size/XS, lgtm

#33 Add Testing Documentation
  README.md
  docs/README.md
  docs/contributor/00-00-overview.md
  docs/contributor/01-00-testing.md
  docs/contributor/README.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: cla: yes, size/M, lgtm

#41 Update go version for EPP binary
  .github/workflows/e2e.yml
  Dockerfile
Labels: cla: yes, size/XS, lgtm

#43 Bump image for 1.0.0 release
  sec-scanners-config.yaml
Labels: cla: yes, size/XS, lgtm

#44 Bump image for epp 1.0.0 release (#43)
  sec-scanners-config.yaml
Labels: cla: yes, size/XS, lgtm

#48 Fix link to NATS CR
  .github/workflows/e2e.yml
Labels: cla: yes, size/XS, lgtm

#49 Make readiness state of EPP dependant on availability of NATS
  pkg/sender/jetstream/health.go
Labels: cla: yes, size/XS, lgtm

#53 Bump image in sec-scanner-config for release 1.0.1
  sec-scanners-config.yaml
Labels: cla: yes, size/XS, lgtm

#54 Merge changes from `main` to release branch
  .github/workflows/e2e.yml
  go.mod
  go.sum
  pkg/sender/jetstream/health.go
  sec-scanners-config.yaml
Labels: cla: yes, size/M, lgtm

#65 Bumped dependencies and changed Eventing CR used in e2e test
  .github/workflows/e2e.yml
  go.mod
  go.sum
Labels: cla: yes, size/M, lgtm

#55 Add golangci-lint config
  .github/workflows/lint-go.yml
  .github/workflows/lint.yml
  .gitignore
  .golangci.yaml
  Makefile
  cmd/eventing-publisher-proxy/main.go
  pkg/application/applicationtest/applicationtest.go
  pkg/application/clean.go
  pkg/application/clean_test.go
  pkg/application/fake/lister.go
  pkg/application/lister.go
  pkg/cloudevents/builder/eventmesh.go
  pkg/cloudevents/builder/eventmesh_test.go
  pkg/cloudevents/builder/generic.go
  pkg/cloudevents/builder/generic_test.go
  pkg/cloudevents/builder/types.go
  pkg/commander/nats/nats.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/handler/handler_v1alpha1_test.go
  pkg/legacy/helpers.go
  pkg/legacy/legacy.go
  pkg/legacy/legacy_test.go
  pkg/nats/connect_test.go
  pkg/oauth/client_test.go
  pkg/receiver/receiver.go
  pkg/receiver/receiver_test.go
  pkg/sender/eventmesh/eventmesh.go
  pkg/sender/eventmesh/eventmesh_test.go
  pkg/sender/jetstream/jetstream_test.go
  pkg/subscribed/helpers.go
  pkg/subscribed/helpers_test.go
  pkg/tracing/helpers.go
  pkg/tracing/helpers_test.go
  testing/fixtures.go
  testing/nats.go
  testing/utils.go
Labels: kind/feature, cla: yes, size/XL, lgtm, area/eventing

#67 Lint fix: dupword
  .github/workflows/lint-go.yml
  cmd/eventing-publisher-proxy/main.go
Labels: cla: yes, size/XS, area/cli, lgtm

#70 Fix lint gomoddirectives & gofumpt
  .github/workflows/lint-go.yml
  README.md
  pkg/application/clean.go
  pkg/cloudevents/builder/eventmesh.go
  pkg/cloudevents/builder/generic.go
  pkg/cloudevents/eventtype/clean.go
  pkg/cloudevents/utils.go
  pkg/handler/handler.go
  pkg/informers/sync.go
  pkg/legacy/legacy.go
  pkg/metrics/collector.go
  pkg/metrics/metricstest/metricstest.go
  pkg/metrics/server.go
  pkg/oauth/client.go
  pkg/sender/eventmesh/eventmesh_test.go
  pkg/sender/helper.go
  pkg/sender/jetstream/jetstream.go
  pkg/subscribed/helpers.go
  pkg/subscribed/processor.go
Labels: cla: yes, size/L, lgtm
